### ISSUE TITLE
AMQP Connection Error

### ISSUE THREAD

**Issue by cstaykov** [ssorj/qtools#5]
I have a rabbitmq docker container running on my machine. I am trying to receive messages in another container running rhel with qtools installed (through yum). I tried `qreceive amqp://guest:guest@10.102.X.X:5672/foo` but received 
```
qreceive-ea87: Error! amqp:connection:framing-error: Expected SASL protocol header got: Unknown protocol ['AMQP\x00\x00\x09\x01']
```

If I use the apt package `amqp-tools` in an ubuntu container, I am able to receive messages using that same address (`amqp-consume --url=amqp://guest:guest@10.102.X.X:5672 -q foo`). Any idea what the problem could be?

**Comment by ssorj** [comment]
The problem there is the AMQP version.  Your server is reporting that it supports 0.9.1, and Qtools supports only 1.0.  You could try enabling 1.0 support in Rabbit, but I haven't tried that myself yet, so I'm not sure it works.
